name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: php-actions/composer@v6
      
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHPStan
        run: composer require --prefer-dist --no-progress --dev phpstan/phpstan
  
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse